### ISSUE TITLE
getElements Botões

### ISSUE THREAD

**Issue by Dylanrichardss** [Dylanrichardss/site-loja#1]
Pretendo colocar dois botões (inputs do HTML) com as mesmas funções JavaScript usando a menor quantidade de espaço no código
Linha com problema: 212

ByClassName e ByName e QuerrySelector já foram tentados. 
Estes getElements acima sem colchetes não funcionou.
Com colchetes, tentei variável vetor mas não funcionou.

Site: https://site-loja.dylanrichardss.repl.co/

![Issue](https://user-images.githubusercontent.com/81787139/133526269-4dd8e4b6-104e-475d-ae2f-05b00c6d0e4c.png)
Obrigado!

**Comment by Raykazan** [comment]
var a = window.document.getElementById('paleta') // 
var bt2 = window.document.getElementById('video');


const bts = [a, bt2];
for (index in bts){
  bts[index].addEventListener('click', clique);
  bts[index].addEventListener('mouseenter', entre);
  bts[index].addEventListener('mouseout', saiu);

}

function clique(){
    this.style.background= 'Black'
    this.style.color='white'
}

function entre(){
    this.style.background= 'lightgrey'
}

function saiu(){
    this.style.background= 'white'
    this.style.color='black'
}

**Comment by Dylanrichardss** [comment]
Obrigado @Raykazan funcionou!
Ajudou no código e no aprendizado :)
